language: cpp
compiler:
    - gcc
# install additional packages
# http://docs.travis-ci.com/user/installing-dependencies/
before_install:
    - curl http://download.opensuse.org/repositories/YaST:/Head:/Travis/xUbuntu_12.04/Release.key | sudo apt-key add -
    - echo "deb http://download.opensuse.org/repositories/YaST:/Head:/Travis/xUbuntu_12.04/ ./" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install --no-install-recommends -y docbook-xsl xsltproc yast2-core-dev yast2-devtools libxcrypt-dev cmake yast2-ycp-ui-bindings-dev ruby2.1 ruby2.1-dev ruby-rspec ruby-fast-gettext
    # http://docs.travis-ci.com/user/common-build-problems/
    - sudo apt-get --reinstall install language-pack-en language-pack-cs
    # disable rvm, use system Ruby
    - rvm reset
script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIB=lib -DCMAKE_VERBOSE_MAKEFILE=ON
    - echo "Using `nproc` jobs"
    - make -j `nproc`
    - (cd tests/ruby && make test ARGS=-V)
    - sudo make install

